### ISSUE TITLE
Update not work?

### ISSUE THREAD

**Issue by crysan** [kodols/php-mysql-library#1]
Hi!

`$db->build('update')->table('tblUsers')->set('book_sel', '=' , '1')->where('id', '=', '1')->execute();`

return
Call to a member function where() on null (0).

And why did several types of operations?

	$db->**build**('update')
		->table('users')
		->set('username','=','ed')
		->set('update_count','=','update_count + 1',true)
		->where('id','=','1234')
		->execute();

	$db->**builder**('update')
		->table('original','a')
		->join('updated','b','innser')
		->on('a.URL','=','b.URL')
		->set('a.funded','=','b.funded',true)
		->set('a.days','=','b.days',true)
		->execute();

**Comment by ed9** [comment]
Hi,

thanks for the heads up, we have made the "SET" chain with the builder, pull down the updated release and you should no longer have this issue.

Regards updating, consider using the simple update method when using a simple approach.

`$db->update('table_name',[
  'col_key' => 'col_value'
],[
  'where_key' => 'where_value'
]);`

**Comment by crysan** [comment]
Ty!!!!!!!!!!
